name: CI Workflow

on:
  pull_request:
      branches:
          - main

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  pre-commit:
    uses: dbt-opiner/dbt-opiner/.github/workflows/pre_commit_flow.yaml@fix-ci-hopefully
  pytest:
    uses: dbt-opiner/dbt-opiner/.github/workflows/pytest_flow.yaml@fix-ci-hopefully
