name: Coveralls Sync

on:
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    pytest_flow:
        name: |
            Coveralls sync workflow
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true

            - name: Install dependencies
              run: poetry install --no-interaction --no-ansi

            - name: pytest
              run: |
                  poetry run pytest --cov-report lcov --cov=dbt_opiner tests/ --numprocesses 10

            - name: Coveralls
              uses: coverallsapp/github-action@v2
