name: Pre-commit

on:
    pull_request:
        branches:
            - main

jobs:
    precommit_flow:
        name: |
            Pre-commit
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Get Changed Files
              id: changed-files
              uses: tj-actions/changed-files@v45

            - name: Run dbt-opiner Linter
              id: dbt-opiner-lint
              env:
                  ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              run: |
                  echo "${ALL_CHANGED_FILES}"

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true

            - name: Install dependencies
              run: poetry install --no-interaction --no-ansi

            - name: pre-commit
              run: |
                  SKIP=run-tox poetry run pre-commit run -a
