name: Pytest

on:
    pull_request:
        branches:
            - main

permissions:
  contents: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    pytest_flow:
        name: |
            Pytest python: ${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version:
                    - '3.10'
                    - '3.11'
                    - '3.12'

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true

            - name: Install dependencies
              run: poetry install --no-interaction --no-ansi

            - name: pytest
              run: |
                  set -o pipefail
                  poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=dbt_opiner tests/ --numprocesses 10 | tee pytest-coverage.txt

            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              if: always()
              with:
                  pytest-coverage-path: ./pytest-coverage.txt
                  title: Coverage Report
                  badge-title: Coverage
                  junitxml-path: ./pytest.xml
